spring.application.name=API-Clima

clima.api.url=https://api.open-meteo.com/v1/forecast
clima.geocoding.url=https://geocoding-api.open-meteo.com/v1/search
clima.cidade=Belo Horizonte - MG
clima.latitude=-19.9167
clima.longitude=-43.9345